# Generated by Django 5.2.1 on 2025-06-05 08:52

import fire_detector.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(upload_to=fire_detector.models.get_upload_path)),
                ('result_file', models.FileField(blank=True, null=True, upload_to=fire_detector.models.get_result_path)),
                ('is_video', models.BooleanField(default=False)),
                ('has_fire', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
